version: '3.8'
services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      - DB_URL=jdbc:postgresql://db:5432/lib_db
#      - DB_USER=user
#      - DB_PASSWORD=password

  db:
    image: postgres:13
    container_name: lib_db_container
    environment:
      POSTGRES_DB: lib_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: